spring:

  datasource:
    url: jdbc:postgresql://localhost:15432/cisq1-lingo
    username: cisq1-lingo
    password: cisq1-lingo

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          charSet: UTF-8
