spring:

#  datasource:
#    url: jdbc:postgresql://database-1.clzqu7hrf207.us-east-1.rds.amazonaws.com:5432/taskdatabasestaging
#    username: taskdatabaseuser
#    password: myg7SRt4cuw4yve
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        connection:
#          charSet: UTF-8
